# Generated by Django 5.0.5 on 2024-05-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0022_useractionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
