# Generated by Django 5.0.5 on 2024-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0023_delete_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashin',
            name='delayed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashout',
            name='delayed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
